apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-spring-boot-skaffold
spec:
  content:
    files: github.com/vrabbi/lab-spring-boot-k8s-skaffold
    image: jdk11-environment:*
  description: Use Skaffold to create a Spring Boot application and deploy it to Kubernetes
  duration: 60m
  session:
    applications:
      console:
        enabled: false
      docker:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      terminal:
        enabled: true
        layout: split
    ingresses:
    - name: application
      port: 8080
    namespaces:
      budget: large
      security:
        policy: baseline
    resources:
      memory: 2Gi
  title: Skaffold + Spring 101
  url: https://github.com/vrabbi/lab-spring-boot-k8s-skaffold
  vendor: TeraSky
